version: "3"
services:
  jupyter:
    image: jupyter/datascience-notebook
    volumes:
      - ".:/home/jovyan"
      - "./.dockerrc/matplotlibrc:/home/jovyan/.matplotlib/matplotlibrc"
      - "./.dockerrc/IPAexfont00301:/usr/share/fonts/truetype/IPAexfont"
      - "./.dockerrc/start-notebook.sh:/usr/local/bin/start-notebook.sh"
    ports:
      - "8890:8888"
    env_file: .dockerrc/env
    restart: always
    container_name: jupyter
